export {
	type AxisAlignedBox,
	aaBoxArea,
	aaBoxFromXY,
	aaBoxMidpoint,
	aaBoxSVG,
} from './math/geometry/2d/AxisAlignedBox.mts';

export {
	bezier2FromBezier,
	bezier3FromBezier,
	bezierFromBezier2,
	bezierFromBezier3,
	bezierFromLine,
	bezierSVG,
	lineFromBezier,
} from './math/geometry/2d/bezierConversion.mts';

export {
	type Circle,
	circleArea,
	circleBounds,
	circleCircumference,
	circleSVG,
} from './math/geometry/2d/Circle.mts';

export {
	type CubicBezier,
	bezier3At,
	bezier3Bisect,
	bezier3Bounds,
	bezier3Derivative,
	bezier3FromBezier2,
	bezier3FromLine,
	bezier3FromPolylinePtsLeastSquares,
	bezier3FromPolylinePtsLeastSquaresFixEnds,
	bezier3FromPts,
	bezier3FromQuad,
	bezier3LengthEstimate,
	bezier3M,
	bezier3MInv,
	bezier3NormalAt,
	bezier3PolynomialX,
	bezier3PolynomialY,
	bezier3SVG,
	bezier3Split,
	bezier3TangentAt,
	bezier3Translate,
	bezier3TsAtXEq,
	bezier3TsAtYEq,
	bezier3XAt,
	bezier3XTurningPointTs,
	bezier3YAt,
	bezier3YTurningPointTs,
	polynomialFromBezier3Values,
} from './math/geometry/2d/CubicBezier.mts';

export {
	intersectBezier3Circle,
	intersectBezier3CircleFn,
	intersectBezier3Line,
	intersectBezier3Rect,
	intersectNBezier3Circle,
	intersectNBezier3CircleFn,
	isOverlapAABoxCircle,
} from './math/geometry/2d/intersection.mts';

export {
	type LineSegment,
	intersectLineLine,
	lineAt,
	lineBisect,
	lineBounds,
	lineDerivative,
	lineFromPts,
	lineLength,
	lineMidpoint,
	lineNormal,
	lineSVG,
	linePolynomialX,
	linePolynomialY,
	lineSplit,
	lineTangent,
	lineTranslate,
	lineTsAtXEq,
	lineTsAtYEq,
	lineXAt,
	lineYAt,
} from './math/geometry/2d/LineSegment.mts';

export {
	type NormalisedCubicBezier,
	bezier3Normalise,
	nBezier3Area,
	nBezier3At,
	nBezier3Curvature,
	nBezier3Derivative,
	nBezier3InflectionTs,
	nBezier3Moment,
	nBezier3XAt,
	nBezier3YAt,
} from './math/geometry/2d/NormalisedCubicBezier.mts';

export {
	type Polygon,
	polygonSignedArea,
} from './math/geometry/2d/Polygon.mts';

export {
	type PtWithDist,
	type Polyline2D,
	polyline2DFromPolyline,
	polyline2DFromPts,
	polyline2DSVG,
	polylineFromPolyline2D,
} from './math/geometry/2d/Polyline2D.mts';

export {
	PT0,
	type Pt,
	matFromPts,
	ptAdd,
	ptAngle,
	ptCross,
	ptDist,
	ptDist2,
	ptDot,
	ptFromVec,
	ptLen,
	ptLen2,
	ptLerp,
	ptMad,
	ptMid,
	ptMul,
	ptNorm,
	ptReflect,
	ptRot90,
	ptSVG,
	ptSignedAngle,
	ptSub,
	ptTransform,
	ptsFromMat,
	vecFromPt,
} from './math/geometry/2d/Pt.mts';

export {
	type QuadraticBezier,
	bezier2At,
	bezier2Bisect,
	bezier2Bounds,
	bezier2Derivative,
	bezier2FromLine,
	bezier2FromPolylinePtsLeastSquares,
	bezier2FromPolylinePtsLeastSquaresFixEnds,
	bezier2FromPts,
	bezier2LengthEstimate,
	bezier2M,
	bezier2MInv,
	bezier2NormalAt,
	bezier2PolynomialX,
	bezier2PolynomialY,
	bezier2SVG,
	bezier2Split,
	bezier2TangentAt,
	bezier2Translate,
	bezier2TsAtXEq,
	bezier2TsAtYEq,
	bezier2XAt,
	bezier2XTurningPointTs,
	bezier2YAt,
	bezier2YTurningPointTs,
	polynomialFromBezier2Values,
} from './math/geometry/2d/QuadraticBezier.mts';

export {
	type Rectangle,
	rectArea,
	rectBounds,
	rectFromAABox,
	rectFromLine,
	rectSVG,
} from './math/geometry/2d/Rectangle.mts';

export { matProjectVec3 } from './math/geometry/3d/projection.mts';

export {
	matFromEyeTargetUp,
	matFromRotationBetween,
	matSkewSymmetricCrossProduct,
} from './math/geometry/3d/rotation.mts';

export {
	type Bezier,
	bezierAt,
	bezierAtMulti,
	bezierBisect,
	bezierDerivative,
	bezierElevateOrder,
	bezierElevateOrderTo,
	bezierFrenetNormalAt,
	bezierFromEndpoints,
	bezierFromPolylineVertsLeastSquares,
	bezierFromPolylineVertsLeastSquaresFixEnds,
	bezierFromQuad,
	bezierFromVecs,
	bezierLowerOrder,
	bezierM,
	bezierMInv,
	bezierNormalAt,
	bezierOrder,
	bezierPolynomials,
	bezierSplit,
	bezierTangentAt,
	bezierTranslate,
	polynomialFromBezierValues,
} from './math/geometry/Bezier.mts';

export {
	type Polyline,
	type VectorWithDist,
	polylineFromVecs,
} from './math/geometry/Polyline.mts';

export { binomial } from './math/binomial.mts';

export {
	type ComplexNumber,
	addZ,
	addZR,
	divRZ,
	divZ,
	expZ,
	invZ,
	mulZ,
	mulZR,
	negZ,
	subRZ,
	subZ,
} from './math/complex.mts';

export {
	mat1Eigenvalues,
	mat1Eigenvector,
	mat2Eigenvalues,
	mat2Eigenvector,
	mat3Eigenvalues,
	mat3Eigenvector,
	mat4Eigenvalues,
	mat4Eigenvector,
	matEigenvalues,
	matEigenvector,
} from './math/eigen.mts';

export {
	erf,
	erfZ,
	erfc,
	erfcZ,
	fresnelCIntegral,
	fresnelSIntegral,
	unscaledFresnelCIntegral,
	unscaledFresnelSIntegral,
} from './math/functions.mts';

export {
	MAT1IDENT,
	MAT2IDENT,
	MAT2ROT90,
	MAT3IDENT,
	MAT4IDENT,
	type Matrix,
	type SquareMatrix,
	internalMatFromFlat,
	mat1Determinant,
	mat1Inverse,
	mat1LeftInverse,
	mat1RightInverse,
	mat1Trace,
	mat2Determinant,
	mat2Inverse,
	mat2LeftInverse,
	mat2RightInverse,
	mat2Trace,
	mat3Determinant,
	mat3Inverse,
	mat3LeftInverse,
	mat3RightInverse,
	mat3Trace,
	mat4Determinant,
	mat4Inverse,
	mat4LeftInverse,
	mat4RightInverse,
	mat4Trace,
	matAdd,
	matAddColumnwise,
	matBinaryOp,
	matDeterminant,
	matFrom,
	matFromArray,
	matFromArrayFn,
	matFromDiag,
	matIdent,
	matInverse,
	matLeftInverse,
	matLerp,
	matMid,
	matMinor,
	matMul,
	matMulABTranspose,
	matMulATransposeB,
	matPadIdent,
	matPrint,
	matReshape,
	matRightInverse,
	matScale,
	matScaleAdd,
	matSub,
	matSumDiagDeterminant2,
	matSumDiagDeterminant3,
	matTrace,
	matTranspose,
	matUnaryOp,
	matWindow,
	matZero,
} from './math/Matrix.mts';

export {
	type Polynomial,
	polynomial2Roots,
	polynomial3Roots,
	polynomial4Roots,
	polynomial5Roots,
	polynomial7SignedRoots,
	polynomialAdd,
	polynomialAt,
	polynomialCompanionMat,
	polynomialDerivative,
	polynomialIntegral,
	polynomialMul,
	polynomialRoots,
	polynomialScale,
	polynomialShift,
	polynomialSub,
	polynomialWithSolutions,
} from './math/Polynomial.mts';

export {
	type Quaternion,
	mat3FromQuat,
	mat3FromUnitQuat,
	quatAdd,
	quatConjugate,
	quatDist,
	quatDist2,
	quatDiv,
	quatDot,
	quatExp,
	quatFrom,
	quatFromMat3BestFit,
	quatFromMat3Exact,
	quatFromRotationAround,
	quatInv,
	quatLerp,
	quatLerpShortestPath,
	quatLerpShortestPathUnit,
	quatLerpUnit,
	quatLog,
	quatMad,
	quatMul,
	quatNearest,
	quatNorm,
	quatNorm2,
	quatPrint,
	quatScale,
	quatSlerp,
	quatSlerpShortestPath,
	quatSquad,
	quatSub,
	quatUnit,
	quatVectorNorm,
	quatVectorNorm2,
} from './math/Quaternion.mts';

export {
	type Vector,
	matFromVecArray,
	vec2Cross,
	vec3Cross,
	vecAdd,
	vecAngle,
	vecArrayFromMat,
	vecDist,
	vecDist2,
	vecDot,
	vecFrom,
	vecLen,
	vecLen2,
	vecLerp,
	vecMad,
	vecMid,
	vecMul,
	vecNorm,
	vecPrint,
	vecReflect,
	vecSub,
} from './math/Vector.mts';

export { CurveDrawer } from './tools/CurveDrawer.mts';

export type {
	Decrement,
	DivideWhole,
	Increment,
	Max,
	Multiply,
} from './types/numeric.mts';

export {
	type SizedArray,
	type SizedArrayWithLength,
	type SizeOf,
	zeros,
} from './util/SizedArray.mts';
