export {
	AABOX00,
	type AxisAlignedBox2D,
	aaBox2Area,
	aaBox2Contains,
	aaBox2FromXY,
	aaBox2Grow,
	aaBox2Midpoint,
	aaBox2SVG,
} from './math/geometry/2d/AxisAlignedBox2D.mts';

export { bezierSVG } from './math/geometry/2d/bezierConversion.mts';

export {
	type Circle,
	ballFromCircle,
	circleArea,
	circleBounds,
	circleCircumference,
	circleContains,
	circleFromBall,
	circleSVG,
	intersectCircleCircle,
	intersectLine2Circle,
	intersectLineSeg2Circle,
} from './math/geometry/2d/Circle.mts';

export {
	type CubicBezier,
	bezier3At,
	bezier3Bisect,
	bezier3Bounds,
	bezier3Derivative,
	bezier3FromBezier,
	bezier3FromBezier2,
	bezier3FromLine,
	bezier3FromPolylinePtsLeastSquares,
	bezier3FromPolylinePtsLeastSquaresFixEnds,
	bezier3FromPts,
	bezier3FromQuad,
	bezier3InflectionTs,
	bezier3LengthEstimate,
	bezier3M,
	bezier3MInv,
	bezier3NormalAt,
	bezier3OpenArea,
	bezier3PolynomialX,
	bezier3PolynomialY,
	bezier3RMSDistance,
	bezier3SVG,
	bezier3Scale,
	bezier3SignedArea,
	bezier3Split,
	bezier3Subdivide,
	bezier3SubdivideBezier2,
	bezier3TangentAt,
	bezier3Transform,
	bezier3Translate,
	bezier3TsAtXEq,
	bezier3TsAtYEq,
	bezier3XAt,
	bezier3XTurningPointTs,
	bezier3YAt,
	bezier3YTurningPointTs,
	bezierFromBezier3,
	polynomialFromBezier3Values,
} from './math/geometry/2d/CubicBezier.mts';

export {
	type CircleIntersectionFn,
	cutBezier3Circle,
	cutBezier3Rect,
	intersectBezier3Circle,
	intersectBezier3CircleFn,
	intersectBezier3LineSeg2,
	intersectBezier3Rect,
	intersectNBezier3Circle,
	intersectNBezier3CircleFn,
	isOverlapAABox2,
	isOverlapAABox2Circle,
	isOverlapAABox2CircleR2,
} from './math/geometry/2d/intersection.mts';

export {
	type Line2D,
	bezierFromLine2,
	intersectLine2Line2,
	line2At,
	line2Bounds,
	line2Derivative,
	line2FromBezier,
	line2FromPts,
	line2Normal,
	line2PolynomialX,
	line2PolynomialY,
	line2SVG,
	line2Scale,
	line2TNearestPt,
	line2Tangent,
	line2Transform,
	line2Translate,
	line2TsAtXEq,
	line2TsAtYEq,
	line2XAt,
	line2YAt,
} from './math/geometry/2d/Line2D.mts';

export {
	intersectLineSeg2LineSeg2,
	lineSeg2Bisect,
	lineSeg2Length,
	lineSeg2Midpoint,
	lineSeg2OpenArea,
	lineSeg2Split,
	lineSeg2TNearestPt2,
} from './math/geometry/2d/LineSegment2D.mts';

export {
	type NormalisedCubicBezier,
	bezier3Normalise,
	nBezier3Area,
	nBezier3At,
	nBezier3Curvature,
	nBezier3Derivative,
	nBezier3InflectionTs,
	nBezier3Moment,
	nBezier3XAt,
	nBezier3YAt,
} from './math/geometry/2d/NormalisedCubicBezier.mts';

export {
	type Polygon,
	polygonContains,
	polygonSignedArea,
} from './math/geometry/2d/Polygon.mts';

export {
	type PointWithDist2D,
	type Polyline2D,
	polyline2DFromPolyline,
	polyline2DFromPts,
	polyline2DOpenArea,
	polyline2DSVG,
	polylineFromPolyline2D,
} from './math/geometry/2d/Polyline2D.mts';

export {
	PT00,
	type Point2D,
	matFromPts,
	ptAdd,
	ptAngle,
	ptCross,
	ptDist,
	ptDist2,
	ptDot,
	ptFromVec,
	ptLen,
	ptLen2,
	ptLerp,
	ptMad,
	ptMid,
	ptMul,
	ptNorm,
	ptReflect,
	ptRot90,
	ptSVG,
	ptSignedAngle,
	ptSub,
	ptTransform,
	ptsFromMat,
	vecFromPt,
} from './math/geometry/2d/Point2D.mts';

export {
	type QuadraticBezier,
	bezier2At,
	bezier2Bisect,
	bezier2Bounds,
	bezier2Derivative,
	bezier2FromBezier,
	bezier2FromLine,
	bezier2FromPolylinePtsLeastSquares,
	bezier2FromPolylinePtsLeastSquaresFixEnds,
	bezier2FromPts,
	bezier2LengthEstimate,
	bezier2M,
	bezier2MInv,
	bezier2NormalAt,
	bezier2OpenArea,
	bezier2PolynomialX,
	bezier2PolynomialY,
	bezier2RMSDistance,
	bezier2SVG,
	bezier2Scale,
	bezier2SignedArea,
	bezier2Split,
	bezier2Subdivide,
	bezier2TangentAt,
	bezier2Transform,
	bezier2Translate,
	bezier2TsAtXEq,
	bezier2TsAtYEq,
	bezier2XAt,
	bezier2XTurningPointTs,
	bezier2YAt,
	bezier2YTurningPointTs,
	bezierFromBezier2,
	polynomialFromBezier2Values,
} from './math/geometry/2d/QuadraticBezier.mts';

export {
	type Rectangle,
	rectArea,
	rectBounds,
	rectContains,
	rectFromAABox2,
	rectFromLineSeg2,
	rectSVG,
} from './math/geometry/2d/Rectangle.mts';

export {
	AABOX000,
	type AxisAlignedBox3D,
	aaBox3Contains,
	aaBox3FromXYZ,
	aaBox3Grow,
	aaBox3Midpoint,
	aaBox3Volume,
} from './math/geometry/3d/AxisAlignedBox3D.mts';

export {
	type Line3D,
	bezierFromLine3,
	line3At,
	line3Derivative,
	line3FromBezier,
	line3FromLine,
	line3FromPt3s,
	line3PolynomialX,
	line3PolynomialY,
	line3PolynomialZ,
	line3Scale,
	line3TNearestPt3,
	line3Tangent,
	line3Translate,
	line3TsAtXEq,
	line3TsAtYEq,
	line3TsAtZEq,
	line3XAt,
	line3YAt,
	line3ZAt,
	lineFromLine3,
} from './math/geometry/3d/Line3D.mts';

export {
	lineSeg3Bisect,
	lineSeg3Length,
	lineSeg3Midpoint,
	lineSeg3Split,
	lineSeg3TNearestPt3,
} from './math/geometry/3d/LineSegment3D.mts';

export {
	PT000,
	type Point3D,
	matFromPt3s,
	pt3Add,
	pt3Angle,
	pt3Cross,
	pt3Dist,
	pt3Dist2,
	pt3Dot,
	pt3FromVec,
	pt3Len,
	pt3Len2,
	pt3Lerp,
	pt3Mad,
	pt3Mid,
	pt3Mul,
	pt3Norm,
	pt3Reflect,
	pt3Sub,
	pt3sFromMat,
	vecFromPt3,
} from './math/geometry/3d/Point3D.mts';

export { matProjectVec3 } from './math/geometry/3d/projection.mts';

export {
	matFromEyeTargetUp,
	matFromRotationBetween,
	matSkewSymmetricCrossProduct,
} from './math/geometry/3d/rotation.mts';

export {
	type Sphere,
	ballFromSphere,
	intersectLine3Sphere,
	intersectLineSeg3Sphere,
	sphereArea,
	sphereBounds,
	sphereContains,
	sphereFromBall,
	sphereVolume,
} from './math/geometry/3d/Sphere.mts';

export {
	type AxisAlignedBox,
	aaBoxContains,
	aaBoxGrow,
	aaBoxMidpoint,
} from './math/geometry/AxisAlignedBox.mts';

export {
	type Ball,
	ballBounds,
	ballContains,
	intersectLineBall,
	intersectLineSegBall,
} from './math/geometry/Ball.mts';

export {
	type Bezier,
	bezierAt,
	bezierAtMulti,
	bezierBisect,
	bezierDerivative,
	bezierElevateOrder,
	bezierElevateOrderTo,
	bezierFrenetNormalAt,
	bezierFromEndpoints,
	bezierFromPolylineVertsLeastSquares,
	bezierFromPolylineVertsLeastSquaresFixEnds,
	bezierFromQuad,
	bezierFromVecs,
	bezierLowerOrder,
	bezierM,
	bezierMInv,
	bezierNormalAt,
	bezierOrder,
	bezierPolynomials,
	bezierScale,
	bezierSplit,
	bezierTangentAt,
	bezierTransform,
	bezierTranslate,
	polynomialFromBezierValues,
} from './math/geometry/Bezier.mts';

export {
	type Line,
	bezierFromLine,
	lineAt,
	lineDerivative,
	lineFromBezier,
	lineFromVecs,
	lineScale,
	lineTNearestVec,
	lineTranslate,
} from './math/geometry/Line.mts';

export {
	lineSegBisect,
	lineSegLength,
	lineSegMidpoint,
	lineSegSplit,
	lineSegTNearestVec,
} from './math/geometry/LineSegment.mts';

export {
	type Polyline,
	type VectorWithDist,
	polylineFromVecs,
} from './math/geometry/Polyline.mts';

export { binomial } from './math/binomial.mts';

export {
	type ComplexNumber,
	addZ,
	addZR,
	complexCompanionMat,
	conjugateZ,
	divRZ,
	divZ,
	expZ,
	invZ,
	mulZ,
	mulZR,
	negZ,
	subRZ,
	subZ,
} from './math/complex.mts';

export {
	mat1Eigenvalues,
	mat1Eigenvector,
	mat2Eigenvalues,
	mat2Eigenvector,
	mat3Eigenvalues,
	mat3Eigenvector,
	mat4Eigenvalues,
	mat4Eigenvector,
	matEigenvalues,
	matEigenvector,
} from './math/eigen.mts';

export {
	erf,
	erfZ,
	erfc,
	erfcZ,
	fresnelCIntegral,
	fresnelSIntegral,
	unscaledFresnelCIntegral,
	unscaledFresnelSIntegral,
} from './math/functions.mts';

export {
	MAT1IDENT,
	MAT2IDENT,
	MAT2ROT90,
	MAT3IDENT,
	MAT4IDENT,
	type Matrix,
	type SquareMatrix,
	mat1Determinant,
	mat1Inverse,
	mat1LeftInverse,
	mat1RightInverse,
	mat1Trace,
	mat2Determinant,
	mat2Inverse,
	mat2LeftInverse,
	mat2RightInverse,
	mat2Trace,
	mat3Determinant,
	mat3Inverse,
	mat3LeftInverse,
	mat3RightInverse,
	mat3Trace,
	mat4Determinant,
	mat4Inverse,
	mat4LeftInverse,
	mat4RightInverse,
	mat4Trace,
	matAdd,
	matAddColumnwise,
	matAddScalar,
	matBinaryOp,
	matDeterminant,
	matElementNorm,
	matElementNorm2,
	matFrom,
	matFromArray,
	matFromArrayFn,
	matFromDiag,
	matIdent,
	matInverse,
	matLeftInverse,
	matLerp,
	matMid,
	matMinor,
	matMul,
	matMulABTranspose,
	matMulATransposeB,
	matMulColumnwise,
	matPadIdent,
	matPrint,
	matReshape,
	matRightInverse,
	matScale,
	matScaleAdd,
	matSub,
	matSumDiagDeterminant2,
	matSumDiagDeterminant3,
	matTrace,
	matTranspose,
	matUnaryOp,
	matWindow,
	matZero,
} from './math/Matrix.mts';

export {
	type Polynomial,
	polynomial2Roots,
	polynomial3Roots,
	polynomial3SignedRoots,
	polynomial4Roots,
	polynomial4SignedRoots,
	polynomial5Roots,
	polynomial5SignedRoots,
	polynomial7SignedRoots,
	polynomialAdd,
	polynomialAt,
	polynomialCompanionMat,
	polynomialDerivative,
	polynomialIntegral,
	polynomialMul,
	polynomialRoots,
	polynomialScale,
	polynomialShift,
	polynomialSub,
	polynomialWithSolutions,
} from './math/Polynomial.mts';

export {
	type Quaternion,
	mat3FromQuat,
	mat3FromUnitQuat,
	quatAdd,
	quatConjugate,
	quatDist,
	quatDist2,
	quatDiv,
	quatDot,
	quatExp,
	quatFrom,
	quatFromMat3BestFit,
	quatFromMat3Exact,
	quatFromRotationAround,
	quatInv,
	quatLerp,
	quatLerpShortestPath,
	quatLerpShortestPathUnit,
	quatLerpUnit,
	quatLog,
	quatMad,
	quatMul,
	quatNearest,
	quatNorm,
	quatNorm2,
	quatPrint,
	quatScale,
	quatSlerp,
	quatSlerpShortestPath,
	quatSquad,
	quatSub,
	quatUnit,
	quatVectorNorm,
	quatVectorNorm2,
} from './math/Quaternion.mts';

export {
	type Vector,
	matFromVecArray,
	vec2Cross,
	vec3Cross,
	vecAdd,
	vecAddScalar,
	vecAngle,
	vecArrayFromMat,
	vecDist,
	vecDist2,
	vecDot,
	vecFrom,
	vecLen,
	vecLen2,
	vecLerp,
	vecMad,
	vecMid,
	vecMul,
	vecNorm,
	vecPrint,
	vecReflect,
	vecSub,
} from './math/Vector.mts';

export { movementThrottle } from './tools/movement.mts';
export { penTool } from './tools/penTool.mts';
export { SingleLinkedList } from './tools/SingleLinkedList.mts';

export type {
	Decrement,
	DivideWhole,
	Increment,
	Max,
	Multiply,
	Sign,
} from './types/numeric.mts';

export {
	type SizedArray,
	type SizedArrayWithLength,
	type SizeOf,
	zeros,
} from './util/SizedArray.mts';
